import 'package:flutter/material.dart';
import 'package:flutter_app/core/models/product.dart';

class Generator {

  static final List<Product> list_sushi = [
    new Product("sushi_1", 'assets/images/products/sushi/', 'baked devilfffffffffffffffffffffffff',
        'fish_text', "343p", null, true, false, 1),
    new Product("sushi_2", 'assets/images/products/sushi/', 'baked devil',
        'fish_text', "343p", "503p", false, true, 1),
    new Product("sushi_3", 'assets/images/products/sushi/', 'baked devil',
        'fish_text', "343p", "503p", false, true, 1),
    new Product("sushi_4", 'assets/images/products/sushi/', 'ba', 'fish_text',
        "343p", null, true, false, 1),
    new Product("sushi_5", 'assets/images/products/sushi/',
        'bakewefwfwefwd devil', 'fish_text', "343p", null, true, false, 1),
    new Product("sushi_6", 'assets/images/products/sushi/', 'baked devil',
        'fish_text', "343p", null, true, false, 1),
    new Product("sushi_7", 'assets/images/products/sushi/', 'baked devil',
        'fish_text', "343p", "503p", false, true,  1),
    new Product("sushi_8", 'assets/images/products/sushi/', 'baked devil',
        'fish_text', "343p", "503p", false, true,  1),
  ];

  static final List<Product> list_pizza = [
    new Product("pizza_1", 'assets/images/products/pizza/', 'bakewefwefd devil',
        'fish_text', "343p", "503p", true, false, 1),
    new Product("pizza_2", 'assets/images/products/pizza/', 'bwefwefaked devil',
        'fish_text', "343p", "503p", false, true, 1),
    new Product("pizza_3", 'assets/images/products/pizza/', 'baked devil',
        'fish_text', "343p", null, false, true, 1),
    new Product("pizza_4", 'assets/images/products/pizza/', 'baked devil',
        'fish_text', "343p", "503p", true, false, 1),
    new Product("pizza_5", 'assets/images/products/pizza/', 'bak  f f  f devil',
        'fish_text', "343p", "503p", true, false, 1),
    new Product("pizza_6", 'assets/images/products/pizza/', 'baked devil',
        'fish_text', "343p", "503p", true, false, 1),
    new Product("pizza_7", 'assets/images/products/pizza/',
        'bawefwefewked devil', 'fish_text', "343p", null, false, true, 1),
    new Product("pizza_8", 'assets/images/products/pizza/', 'baked devil',
        'fish_text', "343p", "503p", false, true, 1),
  ];

  static final List<Product> list_packs_and_combos = [
    new Product(
        "packs_and_combos_1",
        'assets/images/products/packs_and_combos/',
        'bakewefwefd devil',
        'fish_text',
        "343p",
        null,
        true,
        false, 1),
    new Product(
        "packs_and_combos_2",
        'assets/images/products/packs_and_combos/',
        'bwefwefaked devil',
        'fish_text',
        "343p",
        null,
        false,
        true, 1),
    new Product(
        "packs_and_combos_3",
        'assets/images/products/packs_and_combos/',
        'baked devil',
        'fish_text',
        "343p",
        "503p",
        false,
        true, 1),
    new Product(
        "packs_and_combos_4",
        'assets/images/products/packs_and_combos/',
        'baked devil',
        'fish_text',
        "343p",
        "503p",
        true,
        false, 1),
    new Product(
        "packs_and_combos_5",
        'assets/images/products/packs_and_combos/',
        'bak  f f  f devil',
        'fish_text',
        "343p",
        null,
        true,
        false, 1),
    new Product(
        "packs_and_combos_6",
        'assets/images/products/packs_and_combos/',
        'baked devil',
        'fish_text',
        "343p",
        "503p",
        true,
        false, 1),
    new Product(
        "packs_and_combos_7",
        'assets/images/products/packs_and_combos/',
        'bawefwefewked devil',
        'fish_text',
        "343p",
        "503p",
        false,
        true, 1),
    new Product(
        "packs_and_combos_8",
        'assets/images/products/packs_and_combos/',
        'baked devil',
        'fish_text',
        "343p",
        "503p",
        false,
        true, 1),
  ];

  static final List<Product> list_rolls = [
    new Product("roll_1", 'assets/images/products/rolls/', 'bakewefwefd devil',
        'fish_text', "343p", null, true, false, 1),
    new Product("roll_2", 'assets/images/products/rolls/', 'bwefwefaked devil',
        'fish_text', "343p", null, false, true, 1),
    new Product("roll_3", 'assets/images/products/rolls/', 'baked devil',
        'fish_text', "343p", "503p", false, true, 1),
    new Product("roll_4", 'assets/images/products/rolls/', 'baked devil',
        'fish_text', "343p", "503p", true, false, 1),
    new Product("roll_5", 'assets/images/products/rolls/', 'bak  f f  f devil',
        'fish_text', "343p", "503p", true, false, 1),
    new Product("roll_6", 'assets/images/products/rolls/', 'baked devil',
        'fish_text', "343p", "503p", true, false, 1),
    new Product("roll_7", 'assets/images/products/rolls/',
        'bawefwefewked devil', 'fish_text', "343p", null, false, true, 1),
    new Product("roll_8", 'assets/images/products/rolls/', 'baked devil',
        'fish_text', "343p", "503p", false, true, 1),
  ];
}
